### ISSUE TITLE
i cant connect to airflow web ui 

### ISSUE THREAD

**Issue by johnfelipe** [finloop/airflow-postgres-superset-on-docker#9]
```
    ports:
      - 5053:8080
```

**Comment by finloop** [comment]
Could you elaborate? What's the issue? Is there any error?

**Comment by johnfelipe** [comment]
i cant open ip:8080 or ip:5053 for enter to airflow app

**Comment by finloop** [comment]
Try this link: http://localhost:5053/ 
If this one doesn't work, show logs from docker

**Comment by johnfelipe** [comment]
> Try this link: http://localhost:5053/ If this one doesn't work, show logs from docker

i cant do that beacuse i have in another host locally 192.168.88.186
may be iptables or something?

**Comment by finloop** [comment]
Then this issue is specific to your setup.

Yes, you may need to configure ip tables. But first make sure that containers are actually running, aka some process is listening on port 5053 (on that host).

**Comment by johnfelipe** [comment]
pls tell me wich command?

docker ps?

is not running dear

**Comment by finloop** [comment]
Yes, docker ps.

If nothing is there then you didn't start the services. Try docker compose up 

I'm closing the issue for now, as it is not related to any software bug or enchantment. Good lock with your setup 🤗
